const CONSTANTS = { 
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SESSION: 'SESSION',
    CLEAN_IMG_SINGUP : 'CLEAN_IMG_SINGUP',
    LOAD_IMG_SINGUP : 'LOAD_IMG_SINGUP',
};

export default CONSTANTS;