const CONSTANTS = { 
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SESSION: 'SESSION',
    CLEAN_IMG_SINGUP : 'CLEAN_IMG_SINGUP',
    LOAD_IMG_SINGUP : 'LOAD_IMG_SINGUP',
    CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dvm6sgg1h/image/upload',
    CLOUDINARY_PRESET: 'qpthxurl',
    LOAD_IMG_PUBLICATION: 'LOAD_IMG_PUBLICATION',
    CLEAN_IMG_PUBLICATION: 'CLEAN_IMG_PUBLICATION',
};

export default CONSTANTS;