const CONSTANTS = { 
    REGISTER: 'REGISTER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SESSION: 'SESSION',
    CLEAN_IMG_SINGUP : 'CLEAN_IMG_SINGUP',
    LOAD_IMG_SINGUP : 'LOAD_IMG_SINGUP',
    CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dvm6sgg1h/image/upload',
    CLOUDINARY_PRESET: 'qpthxurl',
    LOAD_IMG_PUBLICATION: 'LOAD_IMG_PUBLICATION',
    CLEAN_IMG_PUBLICATION: 'CLEAN_IMG_PUBLICATION',
    UPLOAD_PUBLICATION: 'UPLOAD_PUBLICATION',
    DOWNLOAD_PUBLICATION: 'DOWNLOAD_PUBLICATION',
    ADD_PUBLICATION_STORE: 'ADD_PUBLICATION_STORE',
    ADD_AUTHOR_STORE: 'ADD_AUTHOR_STORE',
    ADD_USER_STORE:'ADD_USER_STORE',
    SUCCESS_PUBLICATION_UPLOADED: 'SUCCESS_PUBLICATION_UPLOADED',
    ERROR_PUBLICATION_UPLOADED: 'ERROR_PUBLICATION_UPLOADED',
    CLEAN_PUBLICATION_UPLOADED: 'CLEAN_PUBLICATION_UPLOADED',
};

export default CONSTANTS;